### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by NicoGonzalez94** [Lucas01v/Back-RUM-Rolling#1]
Buenas! como va? encontre algunos comentarios en el codigo,

![image](https://github.com/Lucas01v/Back-RUM-Rolling/assets/166792979/39b8f40a-3324-444f-aa82-1788ffc3b550)

Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Lucas01v** [comment]
Buenas! Se eliminaron los comentarios.
